# Site settings
title: Your awesome title
email: pabloriveraconde@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just another development blog.
  A way to make me learn new things, rethink some ones I already knew,
  Any language/framework is welcome! 
  Ruby, Javascript, Rails, NodeJS, BackboneJS, Sass, CouchDB, MySQL,... even Haskell!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pablorc.github.com" # the base hostname & protocol for your site
twitter_username: pablorc
github_username:  pablorc

# Build settings
markdown: kramdown
