# Site settings
title: Kitten Driven Development
email: pabloriveraconde@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just another development blog made by @pablorc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pablorc.github.com" # the base hostname & protocol for your site
twitter_username: pablorc
github_username:  pablorc

# Build settings
markdown: kramdown
